/**
 * BRAINBANK - First try - Yappucino Style
 * Generated by Arena Agent - Creative Freedom
 * 
 * Project: First try (b6caa60b-fd4f-4537-a603-4ac1038647f8)
 * Voice: Female TikTok yapping, 55s, self-made billionaires takedown
 * Visuals: 7 anime/satirical images with consistent storytelling
 * 
 * PASTE INTO https://shortdingus.vercel.app/playground -> Render -> Download
 */

import { AbsoluteFill, Img, Audio, Sequence, useCurrentFrame, interpolate } from "remotion";

const VOICE_URL = "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/1789982752531-lm1i28ny81.wav?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4LzE3ODk5ODI3NTI1MzEtbG0xaTI4bnk4MS53YXYiLCJzY29wZSI6ImRvd25sb2FkIiwiaWF0IjoxNzg5OTgyNzU4LCJleHAiOjE3OTI1NzQ3NTh9.kNsy0kwHNcxWCi7MEsXJ9A9cJdKoBLCMjg-hRJ7KI4w";

const IMAGES = [
  "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/generated-brainbank-1-myth.png?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4L2dlbmVyYXRlZC1icmFpbmJhbmstMS1teXRoLnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODk5ODM2OTQsImV4cCI6MTc5MjU3NTY5NH0.tPrNtY47QaiKrj5SGM_7MJOIkahaPWK3Jg-EA4Jaqtk",
  "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/generated-brainbank-2-emerald.png?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4L2dlbmVyYXRlZC1icmFpbmJhbmstMi1lbWVyYWxkLnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODk5ODM2OTUsImV4cCI6MTc5MjU3NTY5NX0.-6pRXxOiu0FwdefSVsrXC-TXrbMnHzJN23eBQ43OwYI",
  "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/generated-brainbank-3-garage.png?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4L2dlbmVyYXRlZC1icmFpbmJhbmstMy1nYXJhZ2UucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4OTk4MzY5NSwiZXhwIjoxNzkyNTc1Njk1fQ.CfVu6zvb_8ieGvZv2qeb4VBrqV_Nbg_K_IEGDH5z2iQ",
  "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/generated-brainbank-4-zuck.png?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4L2dlbmVyYXRlZC1icmFpbmJhbmstNC16dWNrLnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODk5ODM2OTYsImV4cCI6MTc5MjU3NTY5Nn0.XJa_ewbbfdQk3Kz0NuGT9Ux3SazC7XG32aVKUTwC-Ug",
  "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/generated-brainbank-5-runway.png?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4L2dlbmVyYXRlZC1icmFpbmJhbmstNS1ydW53YXkucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4OTk4MzY5NiwiZXhwIjoxNzkyNTc1Njk2fQ.dXJ0Xd5pHYp10buSCPbu6Q1puvGijuAW1QuNzx4oQ50",
  "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/generated-brainbank-6-pool.png?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4L2dlbmVyYXRlZC1icmFpbmJhbmstNi1wb29sLnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODk5ODM2OTcsImV4cCI6MTc5MjU3NTY5N30.kCMyEyIm4LvihRHp1d7wXXyV26FWwhc-73k-ugUtvdw",
  "https://rfbrxohavioeaexhztxa.supabase.co/storage/v1/object/sign/studio-media/b6caa60b-fd4f-4537-a603-4ac1038647f8/generated-brainbank-7-safetynet.png?token=eyJraWQiOiI2MDI4MGJlMi00MTk1LTRjMzYtYWFlNi05MjA5YzBhZTYxMjciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJzdHVkaW8tbWVkaWEvYjZjYWE2MGItZmQ0Zi00NTM3LWE2MDMtNGFjMTAzODY0N2Y4L2dlbmVyYXRlZC1icmFpbmJhbmstNy1zYWZldHluZXQucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4OTk4MzY5NywiZXhwIjoxNzkyNTc1Njk3fQ.52LKBAvI79KQwDGcfchDLZ0Q86cnKMu1sY9R7f8Mqmw"
];

const CAPTIONS = [
  {
    "start": 0.112,
    "end": 1.999,
    "text": "Why self-made billionaires aren't.",
    "image_idx": 0
  },
  {
    "start": 2.196,
    "end": 4.179,
    "text": "Every billionaire has the same origin story.",
    "image_idx": 0
  },
  {
    "start": 4.44,
    "end": 5.317,
    "text": "I started with nothing,",
    "image_idx": 0
  },
  {
    "start": 5.498,
    "end": 6.824,
    "text": "just a dream and hard work.",
    "image_idx": 0
  },
  {
    "start": 7.229,
    "end": 7.866,
    "text": "Elon Musk,",
    "image_idx": 1
  },
  {
    "start": 7.983,
    "end": 9.228000000000002,
    "text": "son of a man who owned an",
    "image_idx": 0
  },
  {
    "start": 9.153,
    "end": 11.056000000000001,
    "text": "emerald mine in apartheid South Africa.",
    "image_idx": 1
  },
  {
    "start": 11.493,
    "end": 12.034,
    "text": "Jeff Bezos,",
    "image_idx": 2
  },
  {
    "start": 12.311,
    "end": 15.881,
    "text": "his parents invested $250,000 into Amazon when",
    "image_idx": 2
  },
  {
    "start": 15.725,
    "end": 16.827,
    "text": "it was a garage project.",
    "image_idx": 2
  },
  {
    "start": 17.248,
    "end": 20.93,
    "text": "That's $250,000 in 1995 in a garage.",
    "image_idx": 2
  },
  {
    "start": 21.432,
    "end": 21.972,
    "text": "Very humble.",
    "image_idx": 0
  },
  {
    "start": 22.49,
    "end": 24.922,
    "text": "Self-made Mark Zuckerberg attended one of the",
    "image_idx": 3
  },
  {
    "start": 24.718,
    "end": 26.461000000000002,
    "text": "most elite prep schools in America,",
    "image_idx": 3
  },
  {
    "start": 26.866,
    "end": 28.545,
    "text": "had a private coding tutor at 12,",
    "image_idx": 3
  },
  {
    "start": 28.806,
    "end": 30.228,
    "text": "and his dad was a dentist who",
    "image_idx": 0
  },
  {
    "start": 30.008,
    "end": 31.494,
    "text": "could afford to fund his early projects.",
    "image_idx": 0
  },
  {
    "start": 31.996,
    "end": 34.321999999999996,
    "text": "The average American couldn't survive without a",
    "image_idx": 4
  },
  {
    "start": 34.038,
    "end": 35.510999999999996,
    "text": "salary for 3 weeks.",
    "image_idx": 4
  },
  {
    "start": 35.79,
    "end": 37.632999999999996,
    "text": "These guys had a runway long enough",
    "image_idx": 4
  },
  {
    "start": 37.574,
    "end": 38.003,
    "text": "to fail,",
    "image_idx": 0
  },
  {
    "start": 38.282,
    "end": 38.581999999999994,
    "text": "pivot,",
    "image_idx": 0
  },
  {
    "start": 38.764,
    "end": 39.385999999999996,
    "text": "fail again,",
    "image_idx": 0
  },
  {
    "start": 39.488,
    "end": 40.431,
    "text": "and still be fine.",
    "image_idx": 0
  },
  {
    "start": 40.693,
    "end": 42.278999999999996,
    "text": "That's not a dream and hard work.",
    "image_idx": 0
  },
  {
    "start": 42.526,
    "end": 44.128,
    "text": "That's a safety net that most people",
    "image_idx": 6
  },
  {
    "start": 44.15,
    "end": 45.895999999999994,
    "text": "will never see in their lifetime dressed",
    "image_idx": 0
  },
  {
    "start": 45.982,
    "end": 47.342999999999996,
    "text": "up as a personality trait.",
    "image_idx": 6
  },
  {
    "start": 47.349,
    "end": 49.272999999999996,
    "text": "We don't call someone a self-made swimmer",
    "image_idx": 5
  },
  {
    "start": 49.439,
    "end": 50.784,
    "text": "when they grew up next to a",
    "image_idx": 0
  },
  {
    "start": 50.58,
    "end": 51.282,
    "text": "private pool.",
    "image_idx": 5
  },
  {
    "start": 51.609,
    "end": 52.648999999999994,
    "text": "The water was already there.",
    "image_idx": 5
  },
  {
    "start": 52.75,
    "end": 54.192,
    "text": "We just never talk about the pool.",
    "image_idx": 0
  },
  {
    "start": 54.455,
    "end": 54.754999999999995,
    "text": "Subscribe.",
    "image_idx": 0
  },
  {
    "start": 55.065,
    "end": 55.364999999999995,
    "text": "Bye.",
    "image_idx": 0
  }
];

export default function Video() {
  const frame = useCurrentFrame();
  const fps = 30;
  const time = frame / fps;

  const activeCaption = CAPTIONS.find(c => time >= c.start && time < c.end);
  const activeImageIdx = activeCaption ? activeCaption.image_idx : 0;

  return (
    <AbsoluteFill style={{ backgroundColor: "#08090b", fontFamily: "Inter, system-ui, sans-serif" }}>
      {IMAGES.map((img, idx) => {
        const isActive = idx === activeImageIdx;
        if (!isActive) return null;
        const sceneStart = CAPTIONS.filter(c => c.image_idx === idx)[0]?.start || 0;
        const sceneProgress = Math.max(0, Math.min(1, (time - sceneStart) / 8));
        const zoom = 1.0 + sceneProgress * 0.15;
        
        return (
          <Sequence key={idx} from={0} durationInFrames={Math.ceil(55 * fps)}>
            <AbsoluteFill style={{ overflow: "hidden", opacity: isActive ? 1 : 0 }}>
              <Img
                src={img}
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  transform: `scale(${zoom})`,
                  filter: "contrast(1.1) saturate(1.15)"
                }}
              />
              <AbsoluteFill style={{ background: "linear-gradient(to top, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.5) 40%, rgba(0,0,0,0.2) 100%)" }} />
              <AbsoluteFill style={{ background: "radial-gradient(ellipse at center, transparent 60%, rgba(0,0,0,0.5) 100%)" }} />
            </AbsoluteFill>
          </Sequence>
        );
      })}

      {activeCaption && (
        <AbsoluteFill style={{ justifyContent: "flex-end", alignItems: "center", paddingBottom: 180, paddingLeft: 36, paddingRight: 36 }}>
          <div style={{
            background: activeCaption.text.toLowerCase().includes("billionaire") || activeCaption.text.includes("$250,000") || activeCaption.text.toLowerCase().includes("safety net") || activeCaption.text.toLowerCase().includes("private pool") ? "#fef08a" : "white",
            color: "black",
            padding: "18px 32px",
            borderRadius: 20,
            fontSize: activeCaption.text.length > 40 ? 42 : 52,
            fontWeight: 850,
            lineHeight: 1.15,
            textAlign: "center",
            maxWidth: 920,
            boxShadow: "0 12px 50px rgba(0,0,0,0.7)",
            border: "4px solid black",
            transform: `scale(${interpolate(frame % 20, [0, 10, 20], [1, 1.03, 1])})`,
          }}>
            {activeCaption.text}
          </div>
        </AbsoluteFill>
      )}

      <Sequence from={0} durationInFrames={90}>
        <AbsoluteFill style={{ justifyContent: "flex-start", paddingTop: 50, alignItems: "center" }}>
          <div style={{ background: "#ef4444", color: "white", padding: "8px 20px", borderRadius: 999, fontWeight: 800, fontSize: 20, letterSpacing: 0.5 }}>
            WHY SELF-MADE IS A MYTH
          </div>
        </AbsoluteFill>
      </Sequence>

      <AbsoluteFill style={{ justifyContent: "flex-end" }}>
        <div style={{ height: 6, background: "rgba(255,255,255,0.2)", width: "100%" }}>
          <div style={{ height: "100%", background: "white", width: `${(frame / (55 * 30)) * 100}%` }} />
        </div>
      </AbsoluteFill>

      <AbsoluteFill style={{ justifyContent: "flex-end", paddingBottom: 40 }}>
        <div style={{ textAlign: "center", color: "rgba(255,255,255,0.7)", fontSize: 16, fontWeight: 600 }}>
          brainbank • yappucino • self-made myth
        </div>
      </AbsoluteFill>

      <Audio src={VOICE_URL} />
    </AbsoluteFill>
  );
}
