/**
 * SHORTDINGUS - FULL VIDEO EXAMPLE
 * Generated by Arena Agent Studio (Option A)
 * 
 * Idea: A 30s intern vs CEO sketch about ridiculous loans
 * 
 * This is what Agent Studio should generate:
 * - 5 anime visuals with consistent characters (intern + CEO)
 * - 8 voice lines with 2 distinct voices (nervous intern, smug CEO)
 * - Viral captions with yellow highlights
 * - Ken Burns zooms + progress bar
 * 
 * PASTE THIS INTO /playground - It will render via your existing AWS Lambda
 * 
 * For production: Replace image URLs with Supabase public URLs after upload
 * For now: Uses placeholder colors + captions to show structure - swap in your 5 generated images
 */

import { AbsoluteFill, Img, Audio, Sequence, useCurrentFrame, interpolate } from "remotion";

// In production, these would be Supabase URLs from studio-media bucket
// For demo, we use the 5 images generated in Arena:
// 1. shortdingus-sample-intern.png - intern holding paycheck confused
// 2. shortdingus-sample-ceo.png - CEO handing envelope smug
// 3. shortdingus-agent-3.png - paycheck with hidden fees close-up
// 4. shortdingus-agent-4.png - CEO laughing arms crossed
// 5. shortdingus-agent-5.png - intern holding exit loan invoice

const SCENES = [
  {
    id: "s1",
    start: 0,
    duration: 4,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1080&h=1920&fit=crop", // REPLACE with your Supabase image 1
    caption: "I have steady income.",
    speaker: "intern",
    zoom: [1.0, 1.2],
    highlight: false
  },
  {
    id: "s2",
    start: 4,
    duration: 3,
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1080&h=1920&fit=crop", // REPLACE with image 2
    caption: "Lacks ambition.",
    speaker: "CEO",
    zoom: [1.2, 1.0],
    highlight: true
  },
  {
    id: "s3",
    start: 7,
    duration: 5,
    image: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=1080&h=1920&fit=crop", // REPLACE with image 3
    caption: "Wait, you financed MY salary?",
    speaker: "intern",
    zoom: [1.0, 1.25],
    highlight: true
  },
  {
    id: "s4",
    start: 12,
    duration: 5,
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=1080&h=1920&fit=crop", // REPLACE with image 4
    caption: "Congrats! We've financed your salary.",
    speaker: "CEO",
    zoom: [1.1, 1.0],
    highlight: false
  },
  {
    id: "s5",
    start: 17,
    duration: 5,
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1080&h=1920&fit=crop", // REPLACE with image 5
    caption: "Isn't that illegal?",
    speaker: "intern",
    zoom: [1.0, 1.15],
    highlight: true
  },
  {
    id: "s6",
    start: 22,
    duration: 4,
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1080&h=1920&fit=crop", // REUSE image 4
    caption: "Hahaha... Why teach this in school?",
    speaker: "CEO",
    zoom: [1.15, 1.3],
    highlight: false
  },
  {
    id: "s7",
    start: 26,
    duration: 4,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1080&h=1920&fit=crop", // REUSE image 1
    caption: "Welcome to the team!",
    speaker: "CEO",
    zoom: [1.0, 1.2],
    highlight: true
  }
];

export default function Video() {
  const frame = useCurrentFrame();
  const fps = 30;

  return (
    <AbsoluteFill style={{ backgroundColor: "#08090b" }}>
      {/* Scenes with Ken Burns */}
      {SCENES.map((scene) => {
        const localFrame = frame - scene.start * fps;
        const progress = Math.max(0, Math.min(1, localFrame / (scene.duration * fps)));
        const zoom = scene.zoom[0] + (scene.zoom[1] - scene.zoom[0]) * progress;
        
        return (
          <Sequence key={scene.id} from={scene.start * fps} durationInFrames={scene.duration * fps}>
            <AbsoluteFill style={{ overflow: "hidden" }}>
              <Img
                src={scene.image}
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  transform: `scale(${zoom})`,
                  filter: "contrast(1.05) saturate(1.1)"
                }}
              />
              {/* Gradient for text readability */}
              <AbsoluteFill style={{ background: "linear-gradient(to top, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.4) 50%, transparent 100%)" }} />
              <AbsoluteFill style={{ background: "radial-gradient(ellipse at center, transparent 60%, rgba(0,0,0,0.5) 100%)" }} />
              
              {/* Speaker label */}
              <div style={{
                position: "absolute",
                top: 60,
                left: 30,
                background: scene.speaker === "CEO" ? "#ef4444" : "#22c55e",
                color: "white",
                padding: "6px 14px",
                borderRadius: 999,
                fontSize: 16,
                fontWeight: 700,
                letterSpacing: 0.5
              }}>
                {scene.speaker.toUpperCase()}
              </div>
            </AbsoluteFill>

            {/* Viral caption - yellow highlight for key lines */}
            <AbsoluteFill style={{ justifyContent: "flex-end", alignItems: "center", paddingBottom: 200, paddingLeft: 32, paddingRight: 32 }}>
              <div style={{
                background: scene.highlight ? "#fef08a" : "white",
                color: "black",
                padding: "16px 28px",
                borderRadius: 18,
                fontSize: 52,
                fontWeight: 850,
                lineHeight: 1.1,
                textAlign: "center",
                maxWidth: 900,
                boxShadow: "0 12px 40px rgba(0,0,0,0.6)",
                border: scene.highlight ? "4px solid black" : "none",
                transform: `scale(${interpolate(frame % 30, [0, 15, 30], [1, 1.02, 1])})`
              }}>
                {scene.caption}
              </div>
            </AbsoluteFill>
          </Sequence>
        );
      })}

      {/* Progress bar */}
      <AbsoluteFill style={{ justifyContent: "flex-end" }}>
        <div style={{ height: 6, background: "rgba(255,255,255,0.2)", width: "100%" }}>
          <div style={{ height: "100%", background: "white", width: `${(frame / 900) * 100}%` }} />
        </div>
      </AbsoluteFill>

      {/* Bottom branding */}
      <AbsoluteFill style={{ justifyContent: "flex-end", paddingBottom: 40 }}>
        <div style={{ textAlign: "center", color: "rgba(255,255,255,0.6)", fontSize: 16 }}>
          shortdingus • intern vs CEO • loans are ridiculous
        </div>
      </AbsoluteFill>

      {/* Audio would go here - in production, add <Audio> per scene with Supabase voice URLs */}
      {/* <Audio src="https://your-supabase-voice-url.mp3" /> */}
    </AbsoluteFill>
  );
}
// Config for Remotion Playground - auto-detected
// 1080x1920, 30fps, 30s
