import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Sparkles, Play, Copy, Check, Download, Image as ImageIcon, Mic, FileText, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

const AgentStudio = () => {
  const [idea, setIdea] = useState("A 30s intern vs CEO sketch about ridiculous loans - corporate horror comedy, intern nervous, CEO smug, show how paycheck gets financed");
  const [generating, setGenerating] = useState(false);
  const [step, setStep] = useState<"idle" | "script" | "images" | "voice" | "code" | "done">("idle");
  const [script, setScript] = useState("");
  const [imagePrompts, setImagePrompts] = useState<string[]>([]);
  const [tsxCode, setTsxCode] = useState("");
  const [copied, setCopied] = useState(false);

  const generate = async () => {
    setGenerating(true);
    setStep("script");
    
    // Simulate agent workflow - in production this would call your Arena agent
    await new Promise(r => setTimeout(r, 800));
    
    const mockScript = `INTERN: "Congrats! We financed your salary."
CEO: "Wait, you financed MY salary?"
INTERN: "Yeah, with an exit loan."
CEO: "Isn't that illegal?"
CEO: "Hahaha... why would we teach this in school?"
INTERN: "So I owe money to quit?"
CEO: "Welcome to the team!"`;

    const mockPrompts = [
      "Anime style, young nervous intern early 20s holding paycheck confused in modern office, worried eyes, short dark hair, flat color illustration, bold lines, 9:16 vertical, no text",
      "Anime style, smug CEO 40s expensive suit slicked back hair condescending smile handing envelope to intern, night office city view, dramatic lighting, 9:16 vertical, no text",
      "Anime style, intern looking at paycheck with tiny text showing hidden fees, shocked expression, close-up, office background, flat colors, 9:16 vertical, no text",
      "Anime style, CEO laughing with arms crossed, expensive watch visible, intern in background worried, corporate horror comedy, 9:16 vertical, no text",
      "Anime style, intern holding invoice that says 'exit loan' with confused face, CEO same cheerful smile as opening, ironic, 9:16 vertical, no text"
    ];

    setScript(mockScript);
    setImagePrompts(mockPrompts);
    setStep("images");
    await new Promise(r => setTimeout(r, 600));
    
    setStep("voice");
    await new Promise(r => setTimeout(r, 600));
    
    // Generate TSX code - this is what you paste into Playground
    const generatedTsx = `import { AbsoluteFill, Img, Audio, Sequence, useCurrentFrame, interpolate } from "remotion";

// Generated by Agent Studio - ${new Date().toISOString()}
// Idea: ${idea}
// Paste this into /playground and render via Lambda

const EDL = {
  duration: 30,
  fps: 30,
  width: 1080,
  height: 1920,
  scenes: [
    { id: "s1", start: 0, duration: 6, img: "YOUR_SUPABASE_IMAGE_1_URL", zoom: [1.0, 1.2], caption: "Congrats! We've financed your salary." },
    { id: "s2", start: 6, duration: 6, img: "YOUR_SUPABASE_IMAGE_2_URL", zoom: [1.2, 1.0], caption: "Wait, you financed MY salary?" },
    { id: "s3", start: 12, duration: 6, img: "YOUR_SUPABASE_IMAGE_3_URL", zoom: [1.0, 1.15], caption: "Yeah, with an exit loan." },
    { id: "s4", start: 18, duration: 6, img: "YOUR_SUPABASE_IMAGE_4_URL", zoom: [1.1, 1.3], caption: "Isn't that illegal? Hahaha..." },
    { id: "s5", start: 24, duration: 6, img: "YOUR_SUPABASE_IMAGE_5_URL", zoom: [1.0, 1.2], caption: "Welcome to the team!" },
  ],
  audio: [
    { start: 0, url: "YOUR_SUPABASE_VOICE_INTERN_1", speaker: "intern" },
    { start: 6, url: "YOUR_SUPABASE_VOICE_CEO_1", speaker: "CEO" },
  ]
};

export default function Video() {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill style={{ background: "#08090b" }}>
      {EDL.scenes.map((scene, i) => {
        const progress = Math.max(0, Math.min(1, (frame / 30 - scene.start) / scene.duration));
        const zoom = scene.zoom[0] + (scene.zoom[1] - scene.zoom[0]) * progress;
        return (
          <Sequence key={scene.id} from={scene.start * 30} durationInFrames={scene.duration * 30}>
            <AbsoluteFill style={{ overflow: "hidden" }}>
              <Img src={scene.img} style={{ width: "100%", height: "100%", objectFit: "cover", transform: \`scale(\${zoom})\` }} />
              <AbsoluteFill style={{ background: "linear-gradient(to top, rgba(0,0,0,0.85) 0%, transparent 60%)" }} />
            </AbsoluteFill>
            <AbsoluteFill style={{ justifyContent: "flex-end", alignItems: "center", paddingBottom: 220, paddingLeft: 40, paddingRight: 40 }}>
              <div style={{
                background: i % 2 === 0 ? "#fef08a" : "white",
                color: "black",
                padding: "14px 26px",
                borderRadius: 16,
                fontSize: 48,
                fontWeight: 800,
                textAlign: "center",
                boxShadow: "0 10px 40px rgba(0,0,0,0.5)",
                border: i % 2 === 0 ? "3px solid black" : "none"
              }}>
                {scene.caption}
              </div>
            </AbsoluteFill>
          </Sequence>
        );
      })}
      {EDL.audio.map((a, i) => (
        <Sequence key={i} from={a.start * 30} durationInFrames={300}>
          <Audio src={a.url} />
        </Sequence>
      ))}
      <AbsoluteFill style={{ justifyContent: "flex-end" }}>
        <div style={{ height: 5, background: "rgba(255,255,255,0.2)" }}>
          <div style={{ height: "100%", background: "white", width: \`\${(frame / 900) * 100}%\` }} />
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
}
// END - Paste into Playground, it will auto-detect 1080x1920 30fps 30s
`;

    setTsxCode(generatedTsx);
    setStep("code");
    await new Promise(r => setTimeout(r, 400));
    setStep("done");
    setGenerating(false);
    toast.success("Agent generated everything! Copy TSX to Playground to render.");
  };

  const copyCode = () => {
    navigator.clipboard.writeText(tsxCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast.success("Copied TSX - paste into /playground");
  };

  return (
    <div className="min-h-screen bg-background">
      <header className="flex h-12 items-center justify-between border-b border-border px-3">
        <div className="flex items-center gap-3">
          <Link to="/" className="text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /></Link>
          <div className="h-4 w-px bg-border" />
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-sm font-semibold">Agent Studio</span>
          <Badge variant="secondary" className="text-xs">Feeds Playground</Badge>
        </div>
          <Link to="/playground"><Button size="sm" variant="outline"><Play className="mr-2 h-4 w-4" />Open Playground</Button></Link>
          <Link to="/video-analyzer.html"><Button size="sm" variant="outline"><Zap className="mr-2 h-4 w-4" />Video Analyzer</Button></Link>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-[42%_1fr] h-[calc(100vh-48px)]">
        {/* Left - Chat / Controls */}
        <div className="flex flex-col border-r border-border bg-background">
          <div className="p-4 border-b border-border">
            <h1 className="text-xl font-bold">What video should we make?</h1>
            <p className="text-sm text-muted-foreground mt-1">Agent generates script + visuals + voices + TSX ready for Playground Lambda</p>
          </div>

          <div className="flex-1 p-4 space-y-4 overflow-auto">
            <div>
              <label className="text-xs font-medium uppercase text-muted-foreground">Idea (I have footage OR I need footage)</label>
              <Textarea
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                placeholder="A 30s intern vs CEO sketch about ridiculous loans..."
                className="mt-2 min-h-[100px] bg-card"
              />
            </div>

            <div className="grid grid-cols-2 gap-2">
              <Button onClick={generate} disabled={generating || !idea.trim()} className="w-full">
                {generating ? <><Sparkles className="mr-2 h-4 w-4 animate-spin" />Generating...</> : <><Zap className="mr-2 h-4 w-4" />Generate with Agent</>}
              </Button>
              <Button variant="outline" asChild><Link to="/studio">Use Old Studio</Link></Button>
            </div>

            {step !== "idle" && (
              <div className="space-y-3 pt-4">
                <div className="flex items-center gap-2 text-xs">
                  <div className={`h-2 w-2 rounded-full ${["script","images","voice","code","done"].includes(step) ? "bg-green-500" : "bg-muted"}`} />
                  <span className={step === "script" ? "font-medium" : "text-muted-foreground"}>Script + shot list</span>
                </div>
                <div className="flex items-center gap-2 text-xs">
                  <div className={`h-2 w-2 rounded-full ${["images","voice","code","done"].includes(step) ? "bg-green-500" : "bg-muted"}`} />
                  <span className={step === "images" ? "font-medium" : "text-muted-foreground"}>Generate 5 anime visuals (consistent characters)</span>
                </div>
                <div className="flex items-center gap-2 text-xs">
                  <div className={`h-2 w-2 rounded-full ${["voice","code","done"].includes(step) ? "bg-green-500" : "bg-muted"}`} />
                  <span className={step === "voice" ? "font-medium" : "text-muted-foreground"}>Generate 2 voices (intern nervous, CEO smug) + timecoded captions</span>
                </div>
                <div className="flex items-center gap-2 text-xs">
                  <div className={`h-2 w-2 rounded-full ${["code","done"].includes(step) ? "bg-green-500" : "bg-muted"}`} />
                  <span className={step === "code" ? "font-medium" : "text-muted-foreground"}>Compile Remotion TSX</span>
                </div>
              </div>
            )}

            {script && (
              <Card>
                <CardHeader className="pb-2"><CardTitle className="text-sm flex items-center gap-2"><FileText className="h-4 w-4" />Script</CardTitle></CardHeader>
                <CardContent><pre className="text-xs whitespace-pre-wrap leading-relaxed">{script}</pre></CardContent>
              </Card>
            )}

            {imagePrompts.length > 0 && (
              <Card>
                <CardHeader className="pb-2"><CardTitle className="text-sm flex items-center gap-2"><ImageIcon className="h-4 w-4" />Image Prompts (for Arena agent)</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                  {imagePrompts.map((p, i) => <div key={i} className="text-xs p-2 bg-muted rounded"><span className="font-mono text-primary">[{i+1}]</span> {p}</div>)}
                  <p className="text-xs text-muted-foreground">These get generated via Arena's generate_image tool, uploaded to Supabase, URLs injected into TSX</p>
                </CardContent>
              </Card>
            )}
          </div>
        </div>

        {/* Right - TSX Code */}
        <div className="flex flex-col bg-card/30">
          <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
            <div>
              <p className="text-sm font-medium">Remotion TSX - Ready for Playground</p>
              <p className="text-xs text-muted-foreground">Paste into /playground → Render via Lambda → Download mp4</p>
            </div>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={copyCode} disabled={!tsxCode}>
                {copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />} {copied ? "Copied" : "Copy TSX"}
              </Button>
              <Button size="sm" asChild disabled={!tsxCode}><Link to="/playground"><Download className="mr-2 h-4 w-4" />Open Playground</Link></Button>
            </div>
          </div>

          <div className="flex-1 p-4 overflow-auto">
            {tsxCode ? (
              <pre className="text-xs bg-background border border-border rounded p-4 overflow-auto whitespace-pre-wrap">{tsxCode}</pre>
            ) : (
              <div className="h-full flex items-center justify-center">
                <div className="text-center max-w-md">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center mx-auto mb-4">
                    <Sparkles className="w-8 h-8 text-white" />
                  </div>
                  <p className="font-medium">TSX will appear here</p>
                  <p className="text-sm text-muted-foreground mt-2">Agent generates script + 5 anime visuals + 2 voices + timecoded captions → compiles into one Remotion file you paste into Playground. Your Lambda does the final render.</p>
                  <div className="mt-6 grid grid-cols-3 gap-2 text-xs">
                    <div className="p-3 bg-background border rounded"><Mic className="h-4 w-4 mx-auto mb-1" />Voice gen here</div>
                    <div className="p-3 bg-background border rounded"><ImageIcon className="h-4 w-4 mx-auto mb-1" />Image gen here</div>
                    <div className="p-3 bg-background border rounded"><Play className="h-4 w-4 mx-auto mb-1" />Render in Playground</div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AgentStudio;
